### ISSUE TITLE
Galacticraft Planets - Ore Processing

### ISSUE THREAD

**Issue by Aringarosa** [NFINIT-Development/Planetary#32]
Hello,

some "Galacticraft Planets" Ores are not recognized by Mekanism. So the can not processed i.e. in the Purification Chamber into the corresponding Ore Clump`s. They can processed in the " Thermal Expansion" Pulverizer into the corresponding Ore Dust.

galacticraftplanets:planets:mars
- Copper Ore
- Tin Ore
- Iron Ore

galacticraftplanets:planets:venus
- Copper Ore
- Galena Ore
- Tin Ore
- Quartz Ore

galacticraftplanets:planets:asteroids_block
- Iron Ore

Greetings Ringo

**Comment by kphoenix137** [comment]
This is likely cause by an oredict problem with Galacticraft Planets. Unfortunately due to SpaceCraftX, Galacticraft and any addon mods cannot be updated past a certain version, so this is something we are unable to resolve. Your best bet would be to use Thermal Foundation or Furnace Overhaul for smelting these ores.
