### ISSUE TITLE
Landing on Kepler 22b doesn't return Dragoncraft capsule

### ISSUE THREAD

**Issue by Basedgod199** [NFINIT-Development/Planetary#52]
When i landed on Kepler 22b, first off, instead of coming down in the capsule, i had my parachute open, and after i had touched down, there was a parachest with fuel and 2 barrier items

Edit: On version 1.1.9

![2020-04-01_03 19 50](https://user-images.githubusercontent.com/32063145/78126658-b3c5eb00-73c7-11ea-842f-0aa0e2248f64.png)

**Comment by br1c** [comment]
This is due to a shortcoming in the mod SpaceCraftX, since the mod was not coded to be integrated with mods other than Galacticraft, and ExtraPlanets likewise. Kepler 22b is a dimension added by ExtraPlanets, so they game gets confused and treats the arrival on Kepler 22b as if you were arriving in a Galacticraft Rocket. The slots are occupied by barriers because they would normally be populated by the Galacticraft Rocket you arrived in. This is a compatibility problem entirely. Unfortunately, there is no possible way to fix this problem without the developers of either mod fixing them, and SpaceCraftX has been abandoned and appears as if it will have no future development.

**Comment by kphoenix137** [comment]
This is a known bug due to SpaceCraftX and will never be able to be fixed (Unless Militario decides he's going to work on it again). In the next update, we implemented a workaround that adds a Parachute quest at the end of Venus to prevent the player from dying. To reach Kepler 22b Space Station, you will need to craft the Tier 10 Electric Rocket as seen in Chapter 7. The easiest way to travel between Earth and Kepler 22b would be via the Portality mod, which you will need to set up prior to arriving on Kepler 22b.
