### ISSUE TITLE
Unable to find all the 5 dungeons on Kepler 22b

### ISSUE THREAD

**Issue by Ginopippo** [NFINIT-Development/Planetary#54]
In my word I've only found Military Laboratory and Cyborg Laboratory.
I've traveled for thousand of blocks and only that dungens spawned.
Sorry for the bad English.

**Comment by br1c** [comment]
This is a bug resulting from the loot tables of Kepler 22b chests being configured incorrectly. This problem resulted in the dungeon generator encountering an error upon generation and caused it to not generate entrances to the 3 remaining types of dungeons. Those dungeons still exist, but you will need to download the fix in order to progress in the modpack, since you will not be able to complete the quest where you obtain the Rogue Android Parts.

https://github.com/NFINIT-Development/Planetary/issues/55

**Comment by kphoenix137** [comment]
Hello. Are you referring to Overworld Labs or Kepler 22b Labs? The next update of the Planetary fixes the problems with Kepler 22b Lab entrances and chest loot. We are not aware of any bugs with overworld labs spawning. Please make sure that you're using the latest version of the modpack and get back to us with more details on the matter, if you are still playing.
